### ISSUE TITLE
How does aggregation changes this engine ? 

### ISSUE THREAD

**Issue by humayunjamal** [awslabs/aws-config-engine-for-compliance-as-code#19]

**Comment by jongogogo** [comment]
Currently the aggregation feature is not used. To aggregate today into the Firehose, the engine is using a describe call multi-region on an regular basis.
Are you interested in the Config aggregation? With or without integration with AWS organizations?

**Comment by jongogogo** [comment]
Added Aggregation dashboard. By deploying the engine, you will have visibility on all account via the Aggregator.
