### ISSUE TITLE
object key incorrect in PCI RuleSetName

### ISSUE THREAD

**Issue by electronicalias** [awslabs/aws-config-engine-for-compliance-as-code#3]
In the following file you have the following mistake;

https://github.com/awslabs/aws-config-engine-for-compliance-as-code/blob/f3b4eb6db56cf68894924737f506a5812532e0b1/ruleset-pci-guidance-7-rules/compliance-account-ruleset-setup.yaml#L46

This should be `Ruleset_Status_Reporter` which would match the Zip file contained in this repository, otherwise CloudFormation will fail when it tries to create. Additionally it might be good to keep the .py file available.

**Comment by jongogogo** [comment]
Thanks for spotting this. Corrected!
