### ISSUE TITLE
Initial Deployment issue

### ISSUE THREAD

**Issue by mrxpl0it** [awslabs/aws-config-engine-for-compliance-as-code#39]
I setup the compliance and the application account yamls in the same region but I did add additional regional support in the compliance account. Both CFT's ran successfully. The code pipeline failed to deploy config rule successfully. I have the out error below.

[Container] 2019/06/21 00:25:57 Running command python ./deploy_rule_templates.py $AWS_DEFAULT_REGION $OUTPUT_BUCKET_NO_REGION $ENGINE_RULE_NAME $OTHER_ACTIVE_REGIONS 
Skipping default.json 
Skipping rulesets_list.txt 
Traceback (most recent call last): 
  File "./deploy_rule_templates.py", line 31, in <module> 
    default_template = json.loads(default_template_obj.get()['Body'].read().decode('utf-8')) 
  File "/usr/local/lib/python3.6/site-packages/boto3/resources/factory.py", line 520, in do_action 
    response = action(self, *args, **kwargs) 
  File "/usr/local/lib/python3.6/site-packages/boto3/resources/action.py", line 83, in __call__ 
    response = getattr(parent.meta.client, operation_name)(**params) 
  File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 320, in _api_call 
    return self._make_api_call(operation_name, kwargs) 
  File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 623, in _make_api_call 
    raise error_class(parsed_response, operation_name) 
botocore.errorfactory.NoSuchBucket: An error occurred (NoSuchBucket) when calling the GetObject operation: The specified bucket does not exist 
 
[Container] 2019/06/21 00:25:59 Command did not exit successfully python ./deploy_rule_templates.py $AWS_DEFAULT_REGION $OUTPUT_BUCKET_NO_REGION $ENGINE_RULE_NAME $OTHER_ACTIVE_REGIONS exit status 1 
[Container] 2019/06/21 00:25:59 Phase complete: BUILD State: FAILED 
[Container] 2019/06/21 00:25:59 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: python ./deploy_rule_templates.py $AWS_DEFAULT_REGION $OUTPUT_BUCKET_NO_REGION $ENGINE_RULE_NAME $OTHER_ACTIVE_REGIONS. Reason: exit status 1

**Comment by evannadeau** [comment]
My initial mistake going multi-region was not to run the CFN templates in the second region.  Did you run the CFN templates for both Compliance and Application accounts in your second region?

**Comment by mrxpl0it** [comment]
I have not done that yet. I can give it a try and provide an update.

**Comment by mrxpl0it** [comment]
I updated the compliance account CF by removing the other supported regions configuration and the code pipeline executed successfully.

**Comment by evannadeau** [comment]
OK, so if you want to run multi-region, add the configuration back in, and then run the exact same CFN templates (both Compliance and Application acct) in both regions.  It detects if it is the main region and runs accordingly.

**Comment by mrxpl0it** [comment]
This is now working as expected. I appreciate the help!
