### ISSUE TITLE
RDK-RULE-FUNCTION LAMBDA

### ISSUE THREAD

**Issue by mrxpl0it** [awslabs/aws-config-engine-for-compliance-as-code#43]
The Application Account CFN is failing its update when a rule is added or modified in the compliance code pipline. The below error is shown.

The AWS Lambda function arn:aws:lambda:xxxxxxx:xxxxxxxxxxxxxxxx:function:RDK-Rule-Function-COMPLIANCERULESETLATESTINSTALLED cannot be invoked.

It appears that this section of the CFN is where the issue is. The only modifications to this CFN has been to add the Compliance account #. The Application account CFN shows this as the Lambda name in the compliance account but the Compliance account CFN does not create a Lambda function with this name.

LambdaFunctionName:
    Description: Lambda name in the Compliance Account
    Default: RDK-Rule-Function-COMPLIANCERULESETLATESTINSTALLED
    Type: String

**Comment by mrxpl0it** [comment]
I figure out that this issue occurred because I did not have the default COMPLIANCE_RULESET_LATEST_INSTALLED rule in my pipeline. I hope this will help others that may run into similar issues.

**Comment by hareshn** [comment]
How you have installed that ? any link or procedure available?
