### ISSUE TITLE
Rules not deploying  in Compliance account

### ISSUE THREAD

**Issue by mrxpl0it** [awslabs/aws-config-engine-for-compliance-as-code#44]
When deploying the Application CFN to the main and other regions in the Compliance account, the config rules are not deploying. I am selecting "False" in the DeployAWSConfig parameters section.

**Comment by jongogogo** [comment]
The challenge is likely that the Engine is trying to assume the same role than the one configured on the Config. 

Can you please try to switch the role of the Config Service Regions already enabled to this role: AWSConfigAndComplianceAuditRole-DO-NOT-DELETE

**Comment by mrxpl0it** [comment]
I think the issue may be that role is not in the compliance account. When I select “True” in the DeployAWSConfig parameter in a region that config is not deployed in, the CFN fails, the error message is below. When I deploy the Application CFN in a region that config is enabled, and select “False” in the DeployAWSConfig parameter it deploys successfully, but that IAM Role is not deployed either.
 
I do not have this issue in accounts outside the Compliance account.

I tried to re-create the role, based on the policies in other accounts that are working correctly,

**Comment by jongogogo** [comment]
Added the option to force the deployment of the IAM role in the main region. It will be useful in the case that Config is already enabled in the main region, but not in the other regions.

See merged PR: https://github.com/awslabs/aws-config-engine-for-compliance-as-code/pull/45

**Comment by jongogogo** [comment]
I am closing this, since it should be fixed. Let me know if anything.
